// <auto-generated />
using System;
using MarqSpec.Mcp.TopstepX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MarqSpec.Mcp.TopstepX.Data.Migrations
{
    [DbContext(typeof(TopstepXDbContext))]
    [Migration("20260827071708_DropPriceLevels")]
    partial class DropPriceLevels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarqSpec.Mcp.TopstepX.Data.Entities.BarCoverageRecord", b =>
                {
                    b.Property<string>("Venue")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Instrument")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RangeStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RangeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Venue", "Instrument", "ResolutionMinutes", "RangeStart", "RangeEnd");

                    b.HasIndex("Instrument", "ResolutionMinutes", "RangeStart", "RangeEnd");

                    b.ToTable("BarCoverage", (string)null);
                });

            modelBuilder.Entity("MarqSpec.Mcp.TopstepX.Data.Entities.BarRecord", b =>
                {
                    b.Property<string>("Venue")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Instrument")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("ContractId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Venue", "Instrument", "ResolutionMinutes", "BucketStart");

                    b.HasIndex("Instrument", "ResolutionMinutes", "BucketStart");

                    b.ToTable("Bars", (string)null);
                });

            modelBuilder.Entity("MarqSpec.Mcp.TopstepX.Data.Entities.EmbeddingRecord", b =>
                {
                    b.Property<int>("OwnerKind")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OwnerKind", "OwnerId", "Model");

                    b.ToTable("Embeddings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Embeddings_OwnerKindKnown", "\"OwnerKind\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.Mcp.TopstepX.Data.Entities.IndicatorValueRecord", b =>
                {
                    b.Property<string>("Venue")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Instrument")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Indicator")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("Venue", "Instrument", "ResolutionMinutes", "Indicator", "Period", "BucketStart");

                    b.HasIndex("Instrument", "ResolutionMinutes", "Indicator", "Period", "BucketStart");

                    b.ToTable("IndicatorValues", (string)null);
                });

            modelBuilder.Entity("MarqSpec.Mcp.TopstepX.Data.Entities.ObservationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Instrument")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Instrument", "RecordedAt");

                    b.ToTable("Observations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
